version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=uefadb
    volumes:
      - db:/data/db
    networks:
      - node-webapp-network
  app:
    depends_on:
      - mongodb
    build: .
    container_name: nodejs-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_DB_URL=mongodb://mongodb:27017/uefadb
      - POT_COUNT=4
      - POT_TEAM_COUNT=8
      - SALT_ROUND=8
      - JWT_SECRET=LtKXw23p
      - JWT_TOKEN_ALGORITHM=HS256
      - JWT_ISSUER=hdyq8KhB
      - JWT_AUDIENCE=vdVk9Djm
      - JWT_EXPIRES_IN_AS_MINUTE=60
    stdin_open: true
    tty: true
    networks:
      - node-webapp-network
volumes:
  db:
networks:
  node-webapp-network:
    driver: bridge
